import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';

export default function Home() {
const router = useRouter();


  function toList(){
router.push('/list');
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<button className="btn btn-primary" onClick={toList}>Go to list</button>

    </div>
  )
}
